/*!
* jQuery pinable Plugin v1.2
* http://buildmypinnedsite.com
*
* Copyright 2011, Microsoft
* Licensed under MS-PL.
*
* Date: Thursday June 16 2011 14:54:29 -04
* Legal Notice: Any code provided on this site is "sample code" subject to the MSDN Terms of Use (http://msdn.microsoft.com/en-us/cc300389.aspx). Using this code means you agree to it.
*/
(function($){var settings={closeTitle:"Close",cookieLength:30,cookieName:"iePinning_"+document.domain,debug:false,discStyle:"toast",dragAlt:"Drag me!",logoPath:"/discoverability/images/logo.png",message:"Drag this to your Windows taskbar to enable special IE9 Features.",slideDuration:"fast",useCookie:true},discStyles={toast:'<div class="toast" id="pinning-discoverability"><div class="pinning-content"><img src="{{logoPath}}" alt="{{dragAlt}}" class="msPinSite" /><div class="pinning-main-text">{{message}}</div><a href="#close" class="pinning-hide" title="{{closeTitle}}">close</a></div></div></div>',pushUp:'<div class="push-up" id="pinning-discoverability"><div class="pinning-content"><div class="pinning-bg"><img src="{{logoPath}}" class="msPinSite" alt="{{dragAlt}}" /></div><div class="pinning-desc">{{message}}</div></div><a href="#close" class="pinning-hide" title="{{closeTitle}}">close</a></div>',topHat:'<div class="top-hat" id="pinning-discoverability"><div class="pinning-alignment"><div class="pinning-content"><img src="{{logoPath}}" class="msPinSite" alt="{{dragAlt}}" /><span class="pinning-desc">{{message}}</span><a href="#close" class="pinning-hide" title="{{closeTitle}}">close</a></div></div></div>'};function hideBanner(event){event.preventDefault();settings.banner.slideToggle(settings.slideDuration);if(settings.useCookie){$.cookie(settings.cookieName,settings.cookieValue,{expires:settings.cookieLength});}}function shouldDisplay(){if(settings.debug){return true;}try{if(!window.external.msIsSiteMode()){if(settings.useCookie){if($.cookie(settings.cookieName)!==settings.cookieValue){return true;}else{return false;}}else{return true;}}else{return false;}}catch(ex){return false;}}function showBanner(){if(shouldDisplay()){if(discStyles.hasOwnProperty(settings.discStyle)){var html=eval("discStyles."+settings.discStyle),html=html.replace("{{message}}",settings.message),html=html.replace("{{dragAlt}}",settings.dragAlt),html=html.replace("{{closeTitle}}",settings.closeTitle),html=html.replace("{{logoPath}}",settings.logoPath);settings.banner=$(html);settings.element.append(settings.banner);settings.banner.slideToggle(settings.slideDuration).find(".pinning-hide").bind("click",hideBanner);}else{$.error("Cannot find discoverability style.");}}}var methods={init:function(callerSettings){settings=$.extend(settings,callerSettings);settings.element=this;settings.cookieValue="hidden";settings.banner=undefined;showBanner();},destroy:function(){settings.element.find(".pinning-hide").unbind("click");settings.element=undefined;settings.banner.remove();settings.banner=undefined;}};$.fn.pinable=function(method){if(methods[method]){return methods[method].apply(this,Array.prototype.slice.call(arguments,1));}else{if(typeof method==="object"||!method){return methods.init.apply(this,arguments);}else{$.error("Method "+method+" does not exist on jQuery.tooltip");}}};})(jQuery);